name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      
      # Installation des dépendances
      - name: Install dependencies
        run: npm ci

      # Installation des navigateurs Playwright
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # Exécution des tests Playwright
      - name: Run Playwright tests
        run: npx playwright test
        continue-on-error: true
      
      - name: Extract and compress index.html
        run: |
          cd playwright-report
          tar -czf rapport.tar.gz index.html


      # Envoi du rapport par e-mail
      - name: Send email with the compressed index.html
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: mohamed-aziz.bejaoui@enis.tn
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Playwright Test Report (rapport)
          body: Please find the attached Playwright test report (rapport).
          to: bej9390@gmail.com
          from: mohamed-aziz.bejaoui@enis.tn
          attachments: playwright-report/rapport.tar.gz

      