name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      
      # Installation des dépendances
      - name: Install dependencies
        run: npm ci

      # Installation des navigateurs Playwright
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # Exécution des tests Playwright
      - name: Run Playwright tests
        run: npx playwright test
        continue-on-error: true
      
      # Téléchargement du rapport de test
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      # Compression du rapport
      - name: Compress report
        run: tar -czf playwright-report.tar.gz playwright-report


      # Envoi du rapport par e-mail
      - name: Send email with the report
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: mohamed-aziz.bejaoui@enis.tn
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Playwright Test Report
          body: Please find the attached Playwright test report.
          to: bej939@gmail.com
          from: mohamed-aziz.bejaoui@enis.tn
          attachments: playwright-report.zip

      # Nouvelle section pour la construction et le push de l'image Docker
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      # Construction de l'image Docker
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/playwrightapp:latest .

      # Push de l'image Docker vers Docker Hub
      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/playwrightapp:latest
