name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests 
      run: npx playwright test tests/login.spec.js
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
    - name: Compress report
      run: tar -czf playwright-report.tar.gz -C playwright-report .
    - name: Send email with the report
      if: always()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: mohamed-aziz.bejaoui@enis.tn
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: Playwright Test Report
        body: Please find the attached Playwright test report.
        to: bej939@gmail.com
        from: mohamed-aziz.bejaoui@enis.tn
        attachments: playwright-report.tar.gz
